#tell travis that we need admin rights for executing the docker commands
sudo: required
#tell travis about the different services required, in our case docker is required
services:
  - docker
# tell travis what needs to be done for building the image
before_install:
  - docker build -t renjitclement/docker-react -f Dockerfile.dev .
# tell travis how to execute our test cases
script:
  - docker run renjitclement/docker-react npm run test -- --coverage
#deployment details
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-079701459887"
  bucket_path: "docker-react"
  access_key_id: $aws-key-docker-react
  secret_access_key:
    secure: "$aws-secret-docker-react"
  on:
    branch: master
